resources:
  jobs:
    cpau_file_parse:
      name: parse_cpau_file

      trigger:
        file_arrival:
          url: "/Volumes/personal/raw/cpau_downloads/"
          min_time_between_triggers_seconds: 600

      parameters:
        - name: file_path
          default: "{{job.trigger.file_arrival.location}}"
        - name: model
          default: gemini-3.5-flash-lite

      tasks:
        - task_key: parse
          environment_key: env
          spark_python_task:
            python_file: ${workspace.file_path}/construction/etl/process_file.py
            parameters:
              - "--file"
              - "{{job.parameters.file_path}}"
              - "--model"
              - "{{job.parameters.model}}"
              - "--catalog"
              - "personal"
              - "--schema"
              - "silver"
              - "--volume"
              - "cpau_downloads"
              - "--table"
              - "cpau"
      environments:
        - environment_key: env
          spec:
            client: "5"
            dependencies:
              - -r ${workspace.file_path}/construction/etl/requirements.txt

    fetch_cpau:
      name: fetch_cpau
      schedule:
        quartz_cron_expression: "0 0 21 * * ?"
        timezone_id: "UTC"
        pause_status: UNPAUSED
      tasks:
        - task_key: cpau
          environment_key: env
          spark_python_task:
            python_file: ${workspace.file_path}/construction/etl/fetch_cpau.py
            parameters:
              - "--catalog"
              - "personal"
              - "--volume"
              - "cpau_downloads"
      environments:
        - environment_key: env
          spec:
            client: "5"
            dependencies:
              - -r ${workspace.file_path}/construction/etl/requirements.txt

    dbt_construction:
      name: dbt_construction
      # trigger:
      #   table_update:
      #     table_names:
      #       - personal.silver.cpau
      tasks:
        - task_key: dbt_build
          dbt_task:
            project_directory: ${workspace.file_path}/construction/construction
            commands:
              - dbt deps
              - dbt seed
              - dbt run
            warehouse_id: ${var.warehouse_id}
            catalog: personal
            schema: silver
          environment_key: env
      environments:
        - environment_key: env
          spec:
            client: "5"
            dependencies:
              - dbt-databricks
