usdmep:
  timeseries_start: 2024-01-01
  table_name: usdmep

ipc:
  excel_target_sheet_name: "Índices IPC Cobertura Nacional"
  table_name: ipc
  volume: "ipc_downloads" # hard-coded to be within raw schema
