resources:
  jobs:
    usdmep_job:
      name: fetch_usdmep
      schedule:
        quartz_cron_expression: "0 0 22 * * ?"
        timezone_id: "UTC"
        pause_status: UNPAUSED
      tasks:
        - task_key: usdmep
          environment_key: env
          spark_python_task:
            python_file: ${workspace.file_path}/argmacro/usdmep.py
            parameters:
              - "--catalog"
              - "personal"
              - "--schema"
              - "argmacro"
              - "--table"
              - "usdmep"
              - "--start"
              - ""
      environments:
        - environment_key: env
          spec:
            client: "5"
            dependencies:
              - loguru

    ipc_job:
      name: fetch_ipc
      schedule:
        quartz_cron_expression: "0 0 22 * * ?"
        timezone_id: "UTC"
        pause_status: UNPAUSED
      tasks:
        - task_key: ipc
          environment_key: env
          spark_python_task:
            python_file: ${workspace.file_path}/argmacro/ipc.py
            parameters:
              - "--catalog"
              - "personal"
              - "--schema"
              - "argmacro"
              - "--table"
              - "ipc"
              - "--date"
              - "{{job.start_time.iso_date}}"
      environments:
        - environment_key: env
          spec:
            client: "5"
            dependencies:
              - loguru
              - xlrd

    ipc_views:
      name: create_ipc_views
      trigger:
        table_update:
          table_names:
            - personal.argmacro.ipc
      parameters:
        - name: catalog
          default: personal
        - name: schema
          default: argmacro
      tasks:
        - task_key: ipc_delta_m
          sql_task:
            warehouse_id: ${var.warehouse_id}
            file:
              path: ${workspace.file_path}/argmacro/ipc_delta_m.sql
            parameters:
              catalog: '{{job.parameters.catalog}}'
              schema: '{{job.parameters.schema}}'
        - task_key: ipc_delta_y
          sql_task:
            warehouse_id: ${var.warehouse_id}
            file:
              path: ${workspace.file_path}/argmacro/ipc_delta_y.sql
            parameters:
              catalog: '{{job.parameters.catalog}}'
              schema: '{{job.parameters.schema}}'